# fly.toml app configuration file generated for harpathgroup on 2025-04-15T22:48:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'harpathgroup'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source='sick_jordan_sqlite'
  destination='/mnt/sick_jordan_sqlite'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
